package View;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;
import javafx.stage.Stage;

public class CopyPhotoController {
	@FXML
	private ListView destList;
	@FXML
	private Button copyButton;
	
	public void start(Stage mainStage){
		
	}
	

	// Event Listener on Button[#copyButton].onAction
	@FXML
	public void handle(ActionEvent event) {
		// TODO Autogenerated
	}
}
