package View;

import Model.Album;
import Model.Photo;
import Model.User;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.ListView;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class MovePhotoController {
	@FXML
	private ListView<String> destList;
	@FXML
	private Button moveButton;
	
	private Stage currentStage;
    
    private ObservableList<String> obslist;
    
    private String selectedAlbum;

	
	public void start(Stage mainStage){
		this.update();
		currentStage = mainStage;
		
		destList
        .getSelectionModel()
        .selectedItemProperty()
        .addListener(
        (obs , oldVal, newVal) -> 
        	{this.selectedAlbum = destList.getSelectionModel().getSelectedItem();});
			// shoulnt be called selected user
	}
	
	public void update(){
		obslist = FXCollections.observableArrayList();
		
		for(Album a : User.getCurrentUser().getAlbumList()){
			String s = new String(a.getName());
			if(s==a.getName()){
				System.out.println("not working");
			}
			obslist.add(s);
		}
		
		destList.setItems(obslist);
	}
	
	
	@FXML
	public void handle(ActionEvent e) {
		// TODO Autogenerated
		Button b = (Button)e.getSource();
    	if(b == moveButton){
    		System.out.println(selectedAlbum);
    		System.out.println(Photo.getCurrentPhoto().toString());
    		
    		for(Album a: User.getCurrentUser().getAlbumList()){
    			if(a.getName().equals(selectedAlbum)){
    				//add to new album before removing from old
    				a.addPhotoToAlbum(Photo.getCurrentPhoto());
 
    				Album.getCurrentAlbum().removePhotoFromAlbum(Photo.getCurrentPhoto());
    				//remove method adjusts count

    			}
    		}
    		this.update();
			currentStage.close();
			//doesnt need to be in the loop
    	}
    	
	}
}
