package View;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.ListView;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class MovePhotoController {
	@FXML
	private ListView destList;
	@FXML
	private Button moveButton;

	
	public void start(Stage mainStage){
		
	}
	
	
	@FXML
	public void handle(ActionEvent event) {
		// TODO Autogenerated
	}
}
